### ISSUE TITLE
将项目使用的javascript库和通用的java库改为git submodule的方式依赖

### ISSUE THREAD

**Issue by zizibujuan** [zizibujuan/drip#1]

**Comment by xiaohulu** [comment]
submodule
1. dojo/dojo
2. dojo/dijit
3. dojo/dojox
4. dojo/util
5. mathEditor
6. mathJax
7. server.util
8. dbaccess.mysql
9. jdbc.mysql (已删除)
10. server.build --> server.dependence
11. server.exception(准备删除)
